### PR TITLE
Test coverage for REAL/LREAL AssertArrayEquals variants

### PR DESCRIPTION
**Pull request by DavidHopkinsFbr**
Verification code for [TcUnit PR 36](https://github.com/tcunit/TcUnit/pull/36)

Follows the patterns established for other array equality assertions in the existing verification project (i.e. a mix of passing and failing assertions)

### CODE REVIEW

**Comment by sagatowski** [comment]
David, I've restructured the TcUnit-Verifier quite dramatically since you did a fork. Now it consists of two programs, the TcUnit-Verifier for TwinCAT and the one that actually runs the twinCAT-part written in C#. Is it possible you could add your changes to the new structure?

**Comment by DavidHopkinsFbr** [comment]
Ok, how's this? I added .NET inspectors for the new TwinCAT test cases too.

I examined the output of the TwinCAT verification code and it looks ok. However, when I try to run the .NET verifier, it seems to be getting stuck on the "Waiting for TcUnit-Verifier_TwinCAT to finish running tests..." to finish. I don't know why. Would you mind taking a look?

**Comment by sagatowski** [comment]
Thank you very much David, I'll merge this during the weekend. Regarding the TwinCAT .NET-verifier I know it's still a little flaky so I'm not surprised it is still waiting. I'll take a look at it!

**Comment by sagatowski** [comment]
Same comments as for TcUnit (in other words, create a new fork so we don't have this many amount of commits that are going to mess up the changelog).
I also noticed there are some tests missing in the functin block FB_AssertEveryFailedTestTwiceArrayVersion, the ones for your new arrays are missing. Please add tests there.

**Comment by sagatowski** [comment]
There were some errors in the .NET-tests which gave the following result:
2019-07-25 13:26:12 - Asserting results...
Test suite ArrayPrimitiveTypes does not report: FAILED TEST 'PRG_TEST.ArrayPrimitiveTypes@Test_LREAL_Array2d_DifferInSize', EXP: SIZE = [-4..3,-1..2] (8x4), ACT: SIZE = SIZE = [1..3,0..1] (3x2), MSG: Arrays differ, size of arrays not matching.
Test suite ArrayPrimitiveTypes does not report: FAILED TEST 'PRG_TEST.ArrayPrimitiveTypes@Test_REAL_Array_DifferInContent', EXP: ARRAY[-7] = -23.0, ACT: ARRAY[2] = 24.0,, MSG: Arrays differ
2019-07-25 13:26:22 - Done.

But it was the expected test output that was not correct (see for example SIZE = SIZE = above). I've fixed this now and will commit the change.

**Comment by sagatowski** [comment]
I'll add the missing tests to FB_AssertEveryFailedTestTwiceArrayVersion.

**Comment by sagatowski** [comment]
I've reviewed the code now and have some comments:
Some tests don't have complete arrays, many of them are just filled up with zeroes so it's just a zero to zero comparison which is not optimal.
See for example:
Test_LREAL_Array2d_DifferInSize
which has
    a : ARRAY[-4..3, -1..2] OF LREAL := [64, 98, -32768, 32767, 5478, -378, 42, 6234];

This only fills upp a small amount of the 2D-array. Same thing goes for the 3D-arrays.

Could you update the tests with values where they are filled up?
I'll commit my changes and then I'll leave this PR open so you can do a new fork on the new changes and add these changes. Once this is done I'll close the PR.

**Comment by sagatowski** [comment]
I also think more tests are necessary for the 2D and 3D-arrays to proove that the method that asserts these take the x,y,z into consideration when checking whether the content is different. This declaratation and single test is not enough:
```
METHOD PRIVATE Test_LREAL_Array3d_DifferInContent
VAR
    a : ARRAY[-5..-4,-1..0,0..1] OF LREAL := [42, -23, -32768];
    b : ARRAY[1..2,4..5,6..7] OF LREAL := [42, 24, -32768];
END_VAR
```
First it doesn't even fill the whole array, second it's only a single test that doesn't take into consideration all the different variants of differences (considering the fact that the assert-method that does this check actually iterates through all three dimensions)

**Comment by sagatowski** [comment]
Manually merged. Added additional tests for "TwiceArrayReporting".
Additional tests that are necessary will be added by creation of new issue.

**Comment by sagatowski** [comment]
Issue is available here:
https://github.com/tcunit/TcUnit-Verifier/issues/4

**Comment by DavidHopkinsFbr** [comment]
I overlooked the FB_AssertEveryFailedTestTwiceArrayVersion. What's the purpose of that set of test cases? How is it distinct from the main functional test?

**Comment by sagatowski** [comment]
The only purpose of that is to verify that the exact same assertion for a specific type (for example, assertLREAL2D) for the same test done twice (or more) should not be shown in the log. Because all tests are actually called cyclically, and the check for whether an assertion has already been called is done in the assertion itself (I think) - this test just verifies that we have the same behavior for all types of asserts.

In any case, the tests are added for your new assert-methods :)

**Pull request closed without merging**
