### PR TITLE
Feature/speed up

### PR DESCRIPTION
**Pull request by KubaO**
Fixes Issue #15. To be applied after PR #14 .

### CODE REVIEW

**Comment by sagatowski** [comment]
Great work! Included this PR into the main branch, with some changes:
- Reincluded the 20s delay before closing visual studio. What can happen if this is not included is that the DTE (Visual Studio) process doesn't die off if the user for some reason cancels the verifier (CTRL+C). I've created a screenshot of this while doing CTRL+C three times on the program: https://alltwincat.com/Misc/vs_studio_processes.png. If you happen to find a solution that does not include the Thread.sleep(20s) and that makes the process die completely I'm more than happy to include it.
- Updated the readme.md to correctly describe the new behaviour. Note that I don't even mention the possibility to include the second (string) argument, as the new (reflection) way of doing it makes the string-argument obsolete and we don't want to confuse any user.

I have discovered some new issues now that I've been running 3.1.4024 as well, but I've created a separate issue for this (#18), that has been taken care by of this commit as well. 

Thanks for your contribution!

**Comment by sagatowski** [comment]
By the way, I really like the addition of the new output:
2019-12-08 14:43:01 - ... got 14 report lines so far.
2019-12-08 14:43:02 - ... got 31 report lines so far.
It always annoyed me that I didn't know whether the TwinCAT tester was actually running or not. Now it's much more clear!

**Comment by KubaO** [comment]
I will make another issue for the Ctrl-C interaction, then. We definitely would want no stray processes to be left either way.

**Comment by sagatowski** [comment]
Looking forward to a working solution. I've been struggling with this one and I'm not happy about the 20s sleep either.

**Pull request merged**
