### PR TITLE
Better tests for 2d and 3d array assertions

### PR DESCRIPTION
**Pull request by DavidHopkinsFbr**
This addresses issue #4.

Guilty admission time: the TcUnit-Verifier .NET component isn't working for me right now, because it wants to start the VS2013 shell, which I don't have installed - so the .NET app bombs out before it actually loads TwinCAT XAE. I _think_ I've written the right meta-test coverage (I've inspected the output of the TwinCAT tests and compared it to the .NET meta-tests) but I haven't yet had the time to install VS2013 alongside my VS2015 and VS2017 installs.

Since you have a working environment, would you mind running a quick smoke test on the .NET verifier? If it's not immediately giving a clean result I'll get it working on my system.

### CODE REVIEW

**Comment by DavidHopkinsFbr** [comment]
Ok, I got the verifier working. Looks like I didn't get the metatests perfect the first time, so I'll update this PR.

**Comment by DavidHopkinsFbr** [comment]
This should be good to go for you now. The Verifier completes successfully on my machine.

**Comment by sagatowski** [comment]
Hi David! Sorry for being late with the merge. I tried to merge this, but I got several compiler errors in TcUnit-Verifier.DotNet. The program does not compile:

```
Error	1	Unexpected character '$'	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	27	TcUnit-Verifier
Error	2	Unexpected character '$'	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	31	TcUnit-Verifier
Error	3	Invalid expression term ''	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	27	TcUnit-Verifier
Error	4	) expected	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	28	TcUnit-Verifier
Error	5	Invalid expression term ')'	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	134	TcUnit-Verifier
Error	6	; expected	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	134	TcUnit-Verifier
Error	7	Invalid expression term ''	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	31	TcUnit-Verifier
Error	8	) expected	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	32	TcUnit-Verifier
Error	9	Invalid expression term ')'	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	108	TcUnit-Verifier
Error	10	; expected	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	108	TcUnit-Verifier
Error	11	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	55	28	TcUnit-Verifier
Error	12	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	C:\Code\GitHub_NewTcUnit\TcUnit-Verifier\TcUnit-Verifier_DotNet\TcUnit-Verifier\VisualStudioInstance.cs	68	32	TcUnit-Verifier

```

**Comment by DavidHopkinsFbr** [comment]
Whoops. Used a C# 6 feature, forgot that this project targets VS2013/C# 5.0.

I'm downloading VS2013 with C# support now, so I can make sure there aren't any other issues.

**Comment by DavidHopkinsFbr** [comment]
All good, tested on VS 2013

**Comment by sagatowski** [comment]
Great, will merge (the eight commits into one).
Thank you!

**Comment by sagatowski** [comment]
Squashed & solved in commit 6e950fc.
Thanks David for this excellent work!

**Comment by DavidHopkinsFbr** [comment]
I see the squash process has resulted in it being committed in your name. I suppose I should learn how to pre-squash the commits so you don't have to!

**Comment by sagatowski** [comment]
Yes, I tried to find a way to keep the original name in the squash but didn't manage :/
Needed to squash as it would be quite many commits that would make the commit history look so-so.
Sorry! :-P

**Pull request closed without merging**
